### PR TITLE
Create the documentation for the project

### LINKED ISSUE #21: Write documentation for the project

### PR DESCRIPTION
**Pull request by borosboyo**
- write seperate .md files for the tasks
- create the final pdf from the given template

### CODE REVIEW

**Review by bbalint2000 — APPROVED** [review]
Great documentation.

**Review by gergobarta — APPROVED** [review]
The documentation is great!

**Review by hangyalpeter — APPROVED** [review]
Nice.

**Review by IBarnabas — APPROVED** [review]
Nice documentations

**Pull request merged**
